version: '{branch}.{build}'
branches:
  only:
  - master
  - appveyor
  - w32

image: Visual Studio 2015

environment:
  PHP_SDK_BINARY_TOOLS_VER: php-sdk-2.0.7
  ARCH: x64
  PHP_TS: ""

  matrix:
    - PHP_VER: 7.2
      PHP_FULL_VER: 7.2.0
      VC_VER: vc15
install:
- cmd: cinst wget
build_script:
- cmd: >-
    set PATH=%PATH%;C:\projects\php-sdk\bin;C:\projects\php\bin;C:\projects\php
    
    set TEST_PHP_EXECUTABLE=C:\projects\php\bin\php.exe

    wget https://github.com/OSTC/php-sdk-binary-tools/archive/%PHP_SDK_BINARY_TOOLS_VER%.zip --no-check-certificate -q -O php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER%.zip

    7z x -y php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER%.zip -oC:\projects

    move C:\projects\php-sdk-binary-tools-%PHP_SDK_BINARY_TOOLS_VER% C:\projects\php-sdk
    
    C:\projects\php-sdk\bin\phpsdk_setvars.bat

    wget http://windows.php.net/downloads/releases/php-%PHP_FULL_VER%-%PHP_TS%Win32-%VC_VER%-%ARCH%.zip
    
    7z x -y php-%PHP_FULL_VER%-%PHP_TS%Win32-%VC_VER%-%ARCH%.zip -oC:\projects\php

    wget http://windows.php.net/downloads/releases/php-devel-pack-%PHP_FULL_VER%-%PHP_TS%Win32-%VC_VER%-%ARCH%.zip
    
    7z x -y php-devel-pack-%PHP_FULL_VER%-%PHP_TS%Win32-%VC_VER%-%ARCH%.zip -oC:\projects

    C:\projects\php-%PHP_FULL_VER%-devel-%VC_VER%-%ARCH%\phpize.bat
    
    move configure.js configure.js-tmp
    
    echo var PHP_SANITIZER="no"; var PHP_CONFIG_PROFILE="no"; >configure.js
    
    type configure.js-tmp >>configure.js

    configure.bat --disable-all --enable-psr --with-prefix=C:\projects\php

    nmake
test_script:
- cmd: nmake test
artifacts:
  - path: bin
    name: master
    type: zip
