version: '{branch}.{build}'

branches:
  only:
  - master
  - appveyor
  - w32

platform:
- x86
- x64

environment:
  PHP_SDK_BINARY_TOOLS_VER: php-sdk-2.0.7
  NO_INTERACTION: 1
  REPORT_EXIT_STATUS: 1
  WIN_SDK_SETENV: 'C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd'

  matrix:
    # - PHP_VER: 7.0
    #   PHP_FULL_VER: 7.0.26
    #   VC_VER: vc14
    #   PHP_BUILD_TYPE: Win32
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    # - PHP_VER: 7.0
    #   PHP_FULL_VER: 7.0.26
    #   VC_VER: vc14
    #   PHP_BUILD_TYPE: nts-Win32
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    # - PHP_VER: 7.1
    #   PHP_FULL_VER: 7.1.12
    #   VC_VER: vc14
    #   PHP_BUILD_TYPE: Win32
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    # - PHP_VER: 7.1
    #   PHP_FULL_VER: 7.1.12
    #   VC_VER: vc14
    #   PHP_BUILD_TYPE: nts-Win32
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    # - PHP_VER: 7.2
    #   PHP_FULL_VER: 7.2.0
    #   VC_VER: vc15
    #   PHP_BUILD_TYPE: Win32
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PHP_VER: 7.2
      PHP_FULL_VER: 7.2.0
      VC_VER: vc15
      PHP_BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

install:
#- ps: install-module pscx -scope CurrentUser
- ps: cinst wget pscx
# - ps: refreshenv
- ps: echo $env:PSModulePath
- ps: dir "C:\Program Files (x86)\PowerShell Community Extensions\Pscx3\Pscx"
- ps: dir "C:\Program Files\PowerShell Community Extensions\Pscx3\Pscx"
- ps: $env:PSModulePath = $env:PSModulePath + ";" + "C:\Program Files (x86)\PowerShell Community Extensions\Pscx3\Pscx";
- ps: . .\.ci\env.ps1
- ps: . .\.ci\download.ps1

build_script:
- ps: . .\.ci\build.ps1

test_script:
- cmd: nmake test

after_build:
- ps: . .\.ci\after_build.ps1

artifacts:
  - path: '.\*.zip'
    name: psr
    type: zip
